stages:
  - build-and-test
  - benchmark

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_BIN: /home/gitlab-runner/.local/graal-core/bin/java
  JVMCI_HOME: /home/gitlab-runner/.local/graal-core/
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse/eclipse
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  ANT: "ant -e"

before_script:
  - git submodule update --init

build_and_test_job:
  stage: build-and-test
  tags: [benchmarks, infinity]
  script:
    - ${ANT} tests

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  allow_failure: true
  script:
    - ${ANT} jar
    - rebench --without-nice --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c core-lib/codespeed.conf TruffleSOM
