stages:
  - build-and-test
  - benchmark
  - benchmark-completion

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  ECLIPSE_EXE: /home/gitlab-runner/.local/eclipse/eclipse
  GRAALEE_HOME: /home/gitlab-runner/.asdf/installs/java/oracle-graalvm-21.0.2
  JAVA_HOME: /home/gitlab-runner/.asdf/installs/java/temurin-21.0.2+13.0.LTS

before_script:
  - (cd core-lib && git remote add smarr https://github.com/smarr/SOM.git || true; git fetch --all)
  - git submodule update --init
  - ./som --setup latest-mx
  - export PATH="$PATH:`pwd`/../mx"
  - (cd ../graal/compiler/mxbuild && sudo reown-project.sh) || true
  - |
      COMMIT_ID=`./som --setup truffle-commit-id`
      (cd ../graal && git fetch --all && git reset --hard $COMMIT_ID) || true

test:
  stage: build-and-test
  tags: [yuria]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - rm libs/jvmci || true
    - ./som --setup labsjdk
    - mx build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool
    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - mx tests-nodestats || true
    - mx tests-coverage || true

build:native-interp-ast:
  stage: build-and-test
  tags: [yuria2]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - rm libs/jvmci || true
    - ./som --setup labsjdk
    - mx build
    - mx build-native --no-jit -t AST -bn
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST -g ${GRAALEE_HOME}
    - ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som
    
    # Package and Upload
    - lz4 som-native-interp-ast som-native-interp-ast.lz4
    - lz4 som-native-interp-ast-ee som-native-interp-ast-ee.lz4
    - |
      sftp tmp-artifacts << EOF
        -mkdir incoming/${CI_PIPELINE_ID}/
        put som-native-interp-ast.lz4 incoming/${CI_PIPELINE_ID}/
        put som-native-interp-ast-ee.lz4 incoming/${CI_PIPELINE_ID}/
      EOF

build:native-interp-bc:
  stage: build-and-test
  tags: [yuria3]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - rm libs/jvmci || true
    - ./som --setup labsjdk
    - mx build
    - mx build-native --no-jit -t BC -bn
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t BC -g ${GRAALEE_HOME}
    - ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som
    
    - lz4 som-native-interp-bc som-native-interp-bc.lz4
    - lz4 som-native-interp-bc-ee som-native-interp-bc-ee.lz4
    - |
      sftp tmp-artifacts << EOF
        -mkdir incoming/${CI_PIPELINE_ID}/
        put som-native-interp-bc.lz4 incoming/${CI_PIPELINE_ID}/
        put som-native-interp-bc-ee.lz4 incoming/${CI_PIPELINE_ID}/
      EOF

build:aarch64-test-and-rebench:
  stage: build-and-test
  tags: [zullie1]
  variables:
    ECLIPSE_EXE: /Users/gitlab-runner/.local/eclipse/eclipse
    GRAALEE_HOME: /Users/gitlab-runner/.asdf/installs/awfy/oracle-graalvm-ea-jdk-23.0.0-ea.08/Contents/Home
    JAVA_HOME: /Users/gitlab-runner/.asdf/installs/java/temurin-21.0.2+13.0.LTS

  script:
    - pmset -g live
    - pmset -g systemstate

    - ./som --setup labsjdk
    - mx sforceimport
    - rm libs/jvmci || true
    - ./som --setup labsjdk

    - mx build
    - mx --env libgraal build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool

    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - mx build-native --no-jit -t BC
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som
    
    - mx build-native --no-jit -t BC -g ${GRAALEE_HOME}
    - ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST -g ${GRAALEE_HOME}
    - ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som
    
    - mx tests-nodestats || true
    - mx tests-coverage || true

    - export PATH=$PATH:/Users/gitlab-runner/Library/Python/3.12/bin
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf

benchmark-y1:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [yuria]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - mx --env libgraal build
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast-ee.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc-ee.lz4
    
    - lz4 -d som-native-interp-ast.lz4 som-native-interp-ast
    - lz4 -d som-native-interp-bc.lz4  som-native-interp-bc
    - lz4 -d som-native-interp-ast-ee.lz4 som-native-interp-ast-ee
    - lz4 -d som-native-interp-bc-ee.lz4  som-native-interp-bc-ee

    # Profile
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profiling m:yuria
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf m:yuria
  after_script:
    - sudo reown-project.sh

benchmark-y2:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [yuria2]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - mx --env libgraal build
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast-ee.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc-ee.lz4
    
    - lz4 -d som-native-interp-ast.lz4 som-native-interp-ast
    - lz4 -d som-native-interp-bc.lz4  som-native-interp-bc
    - lz4 -d som-native-interp-ast-ee.lz4 som-native-interp-ast-ee
    - lz4 -d som-native-interp-bc-ee.lz4  som-native-interp-bc-ee

    # Profile
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profiling m:yuria2
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf m:yuria2
  after_script:
    - sudo reown-project.sh

benchmark-y3:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [yuria3]
  script:
    - ./som --setup labsjdk
    - mx sforceimport
    - mx --env libgraal build
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-ast-ee.lz4
    - sftp tmp-artifacts:incoming/${CI_PIPELINE_ID}/som-native-interp-bc-ee.lz4
    
    - lz4 -d som-native-interp-ast.lz4 som-native-interp-ast
    - lz4 -d som-native-interp-bc.lz4  som-native-interp-bc
    - lz4 -d som-native-interp-ast-ee.lz4 som-native-interp-ast-ee
    - lz4 -d som-native-interp-bc-ee.lz4  som-native-interp-bc-ee

    # Profile
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf profiling m:yuria3
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" -c rebench.conf m:yuria3
  after_script:
    - sudo reown-project.sh

report-completion:
  stage: benchmark-completion
  tags: [yuria]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
