name: Tests

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup MX
        run: |
          git clone --depth 1 https://github.com/graalvm/mx.git
          echo "PATH=$PATH:`pwd`/mx" >> "$GITHUB_ENV"

      - name: Get LabsJDK
        run: |
          mx --java-home=$JAVA_HOME_17_X64 get-labsjdk

      - name: Download Eclipse
        run: |
          export ECLIPSE_TAR=eclipse.tar.gz
          export ECLIPSE_URL=https://ftp.fau.de/eclipse/eclipse/downloads/drops4/R-4.27-202303020300/eclipse-SDK-4.27-linux-gtk-x86_64.tar.gz
          curl -L ${ECLIPSE_URL} -o ${ECLIPSE_TAR}
          tar --warning=no-unknown-keyword -C ${GITHUB_WORKSPACE}/.. -xzf ${ECLIPSE_TAR}

      - name: Run Style Gate
        run: |
          export ECLIPSE_EXE=${GITHUB_WORKSPACE}/../eclipse/eclipse
          mx gate --tags style

  test_som:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Setup MX
        run: |
          git clone --depth 1 https://github.com/graalvm/mx.git
          echo "PATH=$PATH:`pwd`/mx" >> "$GITHUB_ENV"
      
      - name: Get LabsJDK
        run: |
          mx --java-home=$JAVA_HOME_17_X64 get-labsjdk
      
      - name: Compile TruffleSOM
        run: |
          mx build --no-native
      
      - name: Tests
        run: |
          mx tests-junit
          mx tests-som
      
      - name: Build native-image tool
        run: |
          mx build-native-image-tool
    
      - name: Test Object Storage System
        run: |
          mx build-native-obj-test
          ./som-obj-storage-tester
          
      
      - name: Tool Tests
        continue-on-error: true
        run: |
          mx tests-nodestats
          mx tesst-coverage
      
      - name: SomSom Tests
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./som -G -cp core-lib/Smalltalk:core-lib/TestSuite:core-lib/SomSom/src/compiler:core-lib/SomSom/src/vm:core-lib/SomSom/src/vmobjects:core-lib/SomSom/src/interpreter:core-lib/SomSom/src/primitives \
            core-lib/SomSom/tests/SomSomTests.som

      - name: Checkout AWFY
        uses: actions/checkout@v3
        with:
          repository: smarr/are-we-fast-yet
          path: are-we-fast-yet
      
      - name: AWFY Test Run
        run: |
          pwd
          export JAVA_HOME=$JAVA_HOME_17_X64
          pip install ReBench
          rebench awfy-test.conf
